name: Generate Module Manifest

on:
  push:
    paths:
      - 'modules/*.py'

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}
      BRANCH: ${{ github.ref_name }}
      BASE_URL: "https://raw.githubusercontent.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate source.json
        run: |
          cat << "EOF" > generate_manifest.py
          import json
          import os
          import re
          from pathlib import Path
          
          # 配置参数
          MODULES_DIR = "modules"
          OUTPUT_FILE = "source.json"
          
          def extract_module_info(file_path):
              """从Python文件中提取模块信息"""
              with open(file_path, 'r', encoding='utf-8') as f:
                  content = f.read()
              
              # 查找类定义 (BaseModule的子类)
              class_match = re.search(r'class\s+(\w+)\(BaseModule\):', content)
              if not class_match:
                  return None
              
              # 查找self.name赋值
              name_match = re.search(r'self\.name\s*=\s*[\'"](.+?)[\'"]', content)
              if not name_match:
                  return None
              
              return {
                  "class_name": class_match.group(1),
                  "name": name_match.group(1)
              }
          
          def main():
              modules = []
              
              for py_file in Path(MODULES_DIR).glob('**/*.py'):
                  if not py_file.is_file():
                      continue
                  
                  # 生成模块ID (移除后缀)
                  module_id = py_file.stem.replace('_module', '')
                  
                  # 提取模块信息
                  info = extract_module_info(py_file)
                  if not info:
                      continue
                  
                  # 构建raw文件URL
                  file_path = py_file.relative_to(MODULES_DIR)
                  raw_url = f"{os.environ['BASE_URL']}/{os.environ['REPO_NAME']}/{os.environ['BRANCH']}/{MODULES_DIR}/{file_path}"
                  
                  modules.append({
                      "id": module_id,
                      "name": info['name'],
                      "url": raw_url
                  })
              
              # 构建最终JSON结构
              manifest = {
                  "name": "${{ vars.MODULE_NAME }}",
                  "id": "${{ vars.MODULE_ID }}",
                  "data": modules
              }
              
              with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
                  json.dump(manifest, f, indent=2, ensure_ascii=False)
              
              print(f"Generated {OUTPUT_FILE} with {len(modules)} modules")
          
          if __name__ == "__main__":
              main()
          EOF

          python generate_manifest.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@example.com"
          git add source.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update source.json"
          git push
