name: Generate Module Manifest

on:
  push:
    paths:
      - 'modules/**/*.py'
      - '.github/workflows/main.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: '触发原因'
        required: false
        default: 'update for web'

permissions:
  contents: write

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}
      BRANCH: ${{ github.ref_name }}
      BASE_URL: "https://raw.githubusercontent.com"
      MODULE_NAME: ${{ vars.MODULE_NAME }}
      MODULE_ID: ${{ vars.MODULE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate source.json
        run: python scripts/generate_manifest.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@example.com"
          git add source.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update source.json [auto]"
          git push
